### ISSUE TITLE
Not Working on 0.61.13

### ISSUE THREAD

**Issue by xnohat** [SiriusXT/trilium-back-to-history#3]
Hi, 

I have setup this script but it not show history button on Trilium version 0.61.13

Got error
```
23:33:53 Uncaught error: Message: Uncaught TypeError: api.runAsyncOnBackendWithManualTransactionHandling is not a function, URL: , Line: 62, Column: 17, Error object: {}, Stack: TypeError: api.runAsyncOnBackendWithManualTransactionHandling is not a function
    at eval (eval at <anonymous> (http://127.0.0.1:37840/assets/v0.61.13/app-dist/desktop.js:2:49738), <anonymous>:62:17)
```

Thanks,

**Comment by ShizCalev** [comment]
Doesn't function for me as well on Trilium Next. Getting a parsing error at line 57.

![image](https://github.com/user-attachments/assets/56cab629-55e6-422d-9940-f9c014df19d6)
